# Site settings
title: Adventures in programming!!
header-img: img/home-bg.png
email: audenrobertson@gmail.com
copyright_name: liquidsword
description: > # this means to ignore newlines until "baseurl:"
  The psychology of coding...
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  liquidsword
learn_profile: liquidsword
email_username: audenrobertson@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
